export enum DEFAULT_ERROR {
    DATA_VALIDATION_ERROR = 'DATA_VALIDATION_ERROR',
    DEFAULT = 'DEFAULT_ERROR',
    INVALID_USER = 'INVALID_USER',
    SEQUELIZE_VALIDATION = 'SEQUELIZE_VALIDATION_ERROR',
}
